openapi: 3.0.3
info:
  title: GTFS Transit API
  description: |-
    A sample REST API for accessing public transit data from a GTFS feed.
    This API allows users to query for agencies, routes, stops, and schedule information.
  version: 1.0.0
  contact:
    name: API Support
    url: https://www.transit-example.com/support
    email: api@transit-example.com
servers:
  - url: https://api.transit-example.com/v1
    description: Production API Server

tags:
  - name: Agencies
    description: Operations related to transit agencies.
  - name: Routes
    description: Operations for retrieving route information.
  - name: Stops
    description: Operations for finding stops and their information.
  - name: Schedules
    description: Operations for retrieving schedule and departure times.

paths:
  /agencies:
    get:
      tags:
        - Agencies
      summary: List all transit agencies
      operationId: getAgencies
      description: Returns a list of all transit agencies available in the feed.
      responses:
        '200':
          description: A list of agencies.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agency'

  /routes:
    get:
      tags:
        - Routes
      summary: Find transit routes
      operationId: getRoutes
      description: Returns a list of transit routes, optionally filtered by agency.
      parameters:
        - name: agencyId
          in: query
          description: The ID of the agency to filter routes by.
          required: false
          schema:
            type: string
            example: "MTA"
      responses:
        '200':
          description: A list of routes that match the criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'

  /stops:
    get:
      tags:
        - Stops
      summary: Find transit stops near a location
      operationId: getStops
      description: Returns a list of stops within a specified radius of a geographic point.
      parameters:
        - name: lat
          in: query
          description: Latitude of the search center.
          required: true
          schema:
            type: number
            format: double
            example: 42.0012
        - name: lon
          in: query
          description: Longitude of the search center.
          required: true
          schema:
            type: number
            format: double
            example: 21.4325
        - name: radius
          in: query
          description: Search radius in meters.
          required: false
          schema:
            type: integer
            default: 500
            example: 500
      responses:
        '200':
          description: A list of nearby stops.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stop'
        '400':
          description: Invalid coordinates provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /stops/{stopId}/departures:
    get:
      tags:
        - Schedules
        - Stops
      summary: Get upcoming departures for a stop
      operationId: getStopDepartures
      description: Returns a list of upcoming departures for a specific stop, including route and trip information.
      parameters:
        - name: stopId
          in: path
          description: The unique ID of the stop.
          required: true
          schema:
            type: string
            example: "STP_GTC_1"
      responses:
        '200':
          description: A list of upcoming scheduled departures.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StopDeparture'
        '404':
          description: Stop not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Agency:
      type: object
      description: A transit agency from the `agency.txt` GTFS file.
      properties:
        agency_id:
          type: string
          description: A unique identifier for the transit agency.
          example: "JSP"
        agency_name:
          type: string
          description: The full name of the transit agency.
          example: "JSP Skopje"
        agency_url:
          type: string
          format: uri
          description: The URL of the transit agency.
          example: "https://jsp.com.mk"
        agency_timezone:
          type: string
          description: The timezone where the agency is located.
          example: "Europe/Skopje"

    Route:
      type: object
      description: A transit route from the `routes.txt` GTFS file.
      properties:
        route_id:
          type: string
          description: A unique identifier for the route.
          example: "R_2"
        agency_id:
          type: string
          description: ID of the agency that operates this route.
          example: "JSP"
        route_short_name:
          type: string
          description: A short name for the route, often a number or letter.
          example: "2"
        route_long_name:
          type: string
          description: The full, descriptive name of the route.
          example: "Автокоманда - Сарај"
        route_type:
          type: integer
          description: |-
            The type of transportation used on this route.
            * `0` - Tram, Streetcar, Light rail
            * `1` - Subway, Metro
            * `2` - Rail
            * `3` - Bus
            * `4` - Ferry
            * `5` - Cable tram
            * `6` - Aerial lift
            * `7` - Funicular
          example: 3
        route_color:
          type: string
          description: The color associated with the route, in hex format.
          example: "FF0000"

    Stop:
      type: object
      description: A transit stop or station from the `stops.txt` GTFS file.
      properties:
        stop_id:
          type: string
          description: Unique identifier for the stop.
          example: "STP_GTC_1"
        stop_name:
          type: string
          description: The name of the stop.
          example: "Рекорд"
        stop_lat:
          type: number
          format: double
          description: The latitude of the stop.
          example: 41.9950
        stop_lon:
          type: number
          format: double
          description: The longitude of the stop.
          example: 21.4310
        wheelchair_boarding:
          type: integer
          description: Information on wheelchair accessibility. `1` for some level of accessibility, `2` for no accessibility.
          example: 1

    StopDeparture:
      type: object
      description: A consolidated object representing a scheduled departure from a stop.
      properties:
        departure_time:
          type: string
          format: time
          description: The scheduled departure time (HH:MM:SS).
          example: "08:15:00"
        route_short_name:
          type: string
          description: The short name of the route for this trip.
          example: "22"
        trip_headsign:
          type: string
          description: The headsign or destination of the trip.
          example: "Лепенец"
        route_id:
          type: string
          example: "R_22"
        trip_id:
          type: string
          example: "T_22_1_A"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: HTTP status code.
        message:
          type: string
          description: A human-readable error message.