services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transitsync
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data